language: cpp
matrix:
    include:
    - os: linux
      dist: bionic
      env:
        - MATRIX_EVAL="CC=gcc && CXX=g++"
        - CXXSTANDARD="c++14"

    - os: linux
      dist: bionic
      env:
        - MATRIX_EVAL="CC=gcc && CXX=g++"
        - CXXSTANDARD="c++17"
            
   # works on Precise and Trusty
    - os: linux
      dist: bionic
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
         - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
         - CXXSTANDARD="c++14"

    - os: linux
      dist: bionic
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
         - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
         - CXXSTANDARD="c++17"

    # Doesn't support cpp17
    - os: linux
      dist: bionic
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
        - CXXSTANDARD="c++14"

before_install:
    - eval "${MATRIX_EVAL}"
#     - os: osx 
#       osx_image: xcode8.2
#     - os: osx 
#       osx_image: xcode8
#     - os: osx 
#       osx_image: xcode7.3
#     - os: osx 
#       osx_image: xcode6.4

sudo: true

notifications:
    email: false

before_install:
    - eval "${MATRIX_EVAL}"

install: 
    ./travis_scripts/installation_script.sh

script:
    ./travis_scripts/build_script.sh
    #- if [ "$TRAVIS_OS_NAME" == "linux" ]; then make check; fi
    #For some reason, make check on OS X + conda fails to respect LD_LIBRARY_PATH,
    #so we'll run the tests manually
    #- if [ "$TRAVIS_OS_NAME" == "osx" ]; then for i in $(find testsuite -type f -perm +111);do $i -r detailed;done; fi
